/*** Eclipse Class Decompiler plugin, copyright (c) 2016 Chen Chao (cnfree2000@hotmail.com) ***/
package atu.testng.reports.enums;

public enum ExceptionDetails {
	org_openqa_selenium_ElementNotVisibleException, org_openqa_selenium_UnsupportedCommandException, org_openqa_selenium_remote_UnreachableBrowserException, org_openqa_selenium_UnhandledAlertException, org_openqa_selenium_support_ui_UnexpectedTagNameException, org_openqa_selenium_firefox_UnableToCreateProfileException, org_openqa_selenium_remote_ScreenshotException, org_openqa_selenium_remote_SessionTerminatedException, org_openqa_selenium_StaleElementReferenceException, org_openqa_selenium_TimeoutException, org_openqa_selenium_interactions_MoveTargetOutOfBoundsException, org_openqa_selenium_XPathLookupException, org_openqa_selenium_InvalidElementStateException, org_openqa_selenium_interactions_InvalidCoordinatesException, org_openqa_selenium_IllegalLocatorException, org_openqa_selenium_chrome_FatalChromeException, org_openqa_selenium_remote_ErrorHandler_UnknownServerException, java_lang_AssertionError, org_openqa_selenium_NoSuchElementException, org_openqa_selenium_NoAlertPresentException, org_openqa_selenium_NoSuchFrameException, org_openqa_selenium_NoSuchWindowException, org_openqa_selenium_WebDriverException;

	private String exceptionInfo;

	public String getExceptionInfo() {
		return this.exceptionInfo;
	}
}